wandb_version: 1

_current_progress_remaining:
  desc: null
  value: -0.006694443144047657
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[   1.         1.         1.         1.         1.         1.\n     1.\
    \         1.         1.         1.         1.         1.\n     1.         1. \
    \        1.         1.         1.         1.\n     1.         1.         1.  \
    \       1.         1.         1.\n     1.         1.         1.         1.   \
    \      1.         1.\n     1.         1.         1.         1.         1.    \
    \     1.\n     1.         1.         1.         1.         1.         1.\n   \
    \  1.         1.         1.         1.         1.         1.\n     1.        \
    \ 1.         1.         1.         1.         1.\n     1.         1.         1.\
    \         1.         1.         1.\n     1.         1.         1.         1. \
    \        1.         1.\n     1.         1.         1.         1.         1.  \
    \       1.\n     1.         1.         1.         1.         1.         1.\n \
    \    1.         1.         1.         1.         1.         1.\n     1.      \
    \   1.         1.         1.         1.         1.\n     9.        11.       270.\
    \         0.         0.         0.\n    30.        90.      -129.28941]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x000001A14102D190>
_n_updates:
  desc: null
  value: 840
_num_timesteps_at_start:
  desc: null
  value: 172032
_total_timesteps:
  desc: null
  value: 177032
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    code_path: code/AirsoftAI/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1649859738
    t:
      1:
      - 1
      - 2
      - 3
      2:
      - 1
      - 2
      - 3
      3:
      - 16
      - 22
      - 35
      4: 3.9.0
      5: 0.12.11
      8:
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf], [inf inf inf inf inf
    inf inf inf inf], (9,), float32)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 64
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001A141044280>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001A14102DC40>
env_name:
  desc: null
  value: CartPole-v1
ep_info_buffer:
  desc: null
  value: 'deque([{''r'': -1001, ''l'': 15, ''t'': 9953.974674}, {''r'': 1001.1, ''l'':
    12, ''t'': 9954.699733}, {''r'': 1001.1, ''l'': 18, ''t'': 9955.744937}, {''r'':
    1001.1, ''l'': 11, ''t'': 9956.220664}, {''r'': -1001, ''l'': 7, ''t'': 9956.658491},
    {''r'': -1001, ''l'': 25, ''t'': 9958.331015}, {''r'': 1001.1, ''l'': 5, ''t'':
    9958.525498}, {''r'': -1001, ''l'': 5, ''t'': 9958.881545}, {''r'': 1001.1, ''l'':
    5, ''t'': 9959.180743}, {''r'': -1001, ''l'': 1, ''t'': 9959.214653}, {''r'':
    1001.1, ''l'': 2, ''t'': 9959.368243}, {''r'': 1001.1, ''l'': 5, ''t'': 9959.6455},
    {''r'': -1001, ''l'': 3, ''t'': 9959.826017}, {''r'': 1001.1, ''l'': 4, ''t'':
    9960.128206}, {''r'': 1001.1, ''l'': 21, ''t'': 9961.811702}, {''r'': 1001.1,
    ''l'': 22, ''t'': 9963.566009}, {''r'': -1001, ''l'': 10, ''t'': 9964.13748},
    {''r'': -1001, ''l'': 15, ''t'': 9965.0261}, {''r'': -1001, ''l'': 22, ''t'':
    9966.314652}, {''r'': 1001.1, ''l'': 32, ''t'': 9968.646416}, {''r'': 1001.1,
    ''l'': 4, ''t'': 9968.89076}, {''r'': -1001, ''l'': 10, ''t'': 9969.420344}, {''r'':
    1001.1, ''l'': 15, ''t'': 9970.517409}, {''r'': 1001.1, ''l'': 1, ''t'': 9970.594204},
    {''r'': 1001.1, ''l'': 4, ''t'': 9970.839547}, {''r'': -1001, ''l'': 9, ''t'':
    9971.6045}, {''r'': 1001.1, ''l'': 11, ''t'': 9972.331554}, {''r'': -1001, ''l'':
    9, ''t'': 9973.070583}, {''r'': 1001.1, ''l'': 10, ''t'': 9973.66399}, {''r'':
    1001.1, ''l'': 1, ''t'': 9973.744771}, {''r'': 1001.1, ''l'': 14, ''t'': 9974.76903},
    {''r'': 1001.1, ''l'': 16, ''t'': 9975.809248}, {''r'': 1001.1, ''l'': 13, ''t'':
    9976.544282}, {''r'': -1001, ''l'': 24, ''t'': 9977.97545}, {''r'': -1001, ''l'':
    12, ''t'': 9978.83515}, {''r'': 1001.1, ''l'': 15, ''t'': 9979.608083}, {''r'':
    1001.1, ''l'': 9, ''t'': 9980.109746}, {''r'': 1001.1, ''l'': 12, ''t'': 9981.096103},
    {''r'': 1001.1, ''l'': 17, ''t'': 9982.304867}, {''r'': 1001.1, ''l'': 20, ''t'':
    9983.500666}, {''r'': -1001, ''l'': 23, ''t'': 9984.597731}, {''r'': -1001, ''l'':
    3, ''t'': 9984.713421}, {''r'': -1001, ''l'': 19, ''t'': 9986.277237}, {''r'':
    1001.1, ''l'': 5, ''t'': 9986.606355}, {''r'': -1001, ''l'': 24, ''t'': 9988.1612},
    {''r'': -1001, ''l'': 7, ''t'': 9988.635929}, {''r'': 1001.1, ''l'': 3, ''t'':
    9988.77356}, {''r'': -1001, ''l'': 13, ''t'': 9989.488647}, {''r'': 1001.1, ''l'':
    35, ''t'': 9991.53118}, {''r'': -1001, ''l'': 5, ''t'': 9991.840353}, {''r'':
    -1001, ''l'': 14, ''t'': 9992.786819}, {''r'': -1001, ''l'': 7, ''t'': 9993.379232},
    {''r'': -1001, ''l'': 31, ''t'': 9995.152492}, {''r'': 1001.1, ''l'': 16, ''t'':
    9996.01119}, {''r'': -1001, ''l'': 27, ''t'': 9997.722611}, {''r'': -1001, ''l'':
    13, ''t'': 9998.553388}, {''r'': -1001, ''l'': 2, ''t'': 9998.71296}, {''r'':
    -1001, ''l'': 10, ''t'': 9999.44202}, {''r'': 1001.1, ''l'': 12, ''t'': 10000.10224},
    {''r'': 1001.1, ''l'': 2, ''t'': 10000.239876}, {''r'': 1001.1, ''l'': 13, ''t'':
    10000.887145}, {''r'': -1001, ''l'': 29, ''t'': 10002.840916}, {''r'': 1001.1,
    ''l'': 18, ''t'': 10004.204266}, {''r'': -1001, ''l'': 22, ''t'': 10005.938627},
    {''r'': 1001, ''l'': 21, ''t'': 10007.302975}, {''r'': 1001.1, ''l'': 79, ''t'':
    10012.175937}, {''r'': 1001.1, ''l'': 15, ''t'': 10013.189224}, {''r'': -1001,
    ''l'': 13, ''t'': 10014.041944}, {''r'': -1001, ''l'': 5, ''t'': 10014.383032},
    {''r'': 1001.1, ''l'': 10, ''t'': 10015.042267}, {''r'': -1001, ''l'': 24, ''t'':
    10016.969117}, {''r'': 1001.1, ''l'': 12, ''t'': 10017.893637}, {''r'': 1001.1,
    ''l'': 2, ''t'': 10017.988383}, {''r'': 1001.1, ''l'': 12, ''t'': 10018.834121},
    {''r'': -1001, ''l'': 3, ''t'': 10018.951806}, {''r'': -1001, ''l'': 1, ''t'':
    10018.981727}, {''r'': 1001.1, ''l'': 9, ''t'': 10019.711773}, {''r'': 1001.1,
    ''l'': 3, ''t'': 10019.873341}, {''r'': -1001, ''l'': 8, ''t'': 10020.251328},
    {''r'': 1001.1, ''l'': 19, ''t'': 10021.563823}, {''r'': 1001.1, ''l'': 6, ''t'':
    10021.994663}, {''r'': -1001, ''l'': 26, ''t'': 10023.817788}, {''r'': 1001.1,
    ''l'': 41, ''t'': 10026.404865}, {''r'': -1001, ''l'': 4, ''t'': 10026.6532},
    {''r'': -1001, ''l'': 7, ''t'': 10026.990297}, {''r'': 1001.1, ''l'': 26, ''t'':
    10028.551121}, {''r'': -1001, ''l'': 15, ''t'': 10029.54546}, {''r'': -1001, ''l'':
    5, ''t'': 10029.853634}, {''r'': 1001.1, ''l'': 7, ''t'': 10030.254565}, {''r'':
    -1001, ''l'': 2, ''t'': 10030.401175}, {''r'': 1001.1, ''l'': 15, ''t'': 10031.423436},
    {''r'': 1001.1, ''l'': 20, ''t'': 10032.453678}, {''r'': 1001.1, ''l'': 15, ''t'':
    10033.55872}, {''r'': -1001, ''l'': 11, ''t'': 10034.432383}, {''r'': -1001, ''l'':
    24, ''t'': 10035.958301}, {''r'': -1001, ''l'': 16, ''t'': 10037.082291}, {''r'':
    -1001, ''l'': 4, ''t'': 10037.354564}, {''r'': 1001.1, ''l'': 10, ''t'': 10038.054695},
    {''r'': 1001.1, ''l'': 10, ''t'': 10038.820639}, {''r'': -1001, ''l'': 24, ''t'':
    10040.474217}], maxlen=100)'
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0003
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x000001A141044310>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 10
n_steps:
  desc: null
  value: 2048
num_timesteps:
  desc: null
  value: 172032
observation_space:
  desc: null
  value: "Box([-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf -inf -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf -inf -inf -inf -inf\
    \ -inf -inf -inf -inf -inf -inf -inf -inf -inf\n -inf], [inf inf inf inf inf inf\
    \ inf inf inf inf inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf\
    \ inf inf inf inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf inf\
    \ inf inf inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf inf inf\
    \ inf inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf inf inf inf\
    \ inf inf inf inf inf inf inf inf\n inf inf inf inf inf inf inf inf inf], (99,),\
    \ float32)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=99,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=99, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=9, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
policy_type:
  desc: null
  value: MlpPolicy
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001A14102DBB0>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1649859741.448749
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: None
total_timesteps:
  desc: null
  value: 5000
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 2
vf_coef:
  desc: null
  value: 0.5
